language: java

sudo: required

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test']
    packages: ['libstdc++6']

install:
  - bash scripts/fetchSo.sh travis
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml'

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify