language: java

install:
  - mvn org.apache.
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

cache:
  directories:
  - .autoconf
  - $HOME/.m2

