language: java

sudo: required


install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get install libstdc++-4.9-dev
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify